defaultBackend: "http://localhost:4070"   # fallback
mappings:
  - frontendHost: "frontend1.example.com"
    backend: "http://backend1.internal:8000"
  - frontendHost: "localhost"
    backend: "http://localhost:8000"
  # Example mapping by path prefix (same host but different apps by path)
  - frontendHost: "localhost"
    pathPrefix: "/immich"
    backend: "http://localhost:9001"
