version: "3.9"
services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  bff:
    build: .
    env_file: .env
    depends_on:
      - redis
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  redis-data:
