services:
  redis:
    image: redis:7-alpine
    container_name: api-get-away-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-get-away:
    build: .
    container_name: api-get-away
    env_file: .env
    depends_on:
      - redis
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=5000
    restart: unless-stopped
