server:
  public_url: ${BFF_PUBLIC_URL}
  encryption_key_b64: ${BFF_ENC_KEY_BASE64}
  cookie_secure: false   # true in prod behind HTTPS
  log_level: debug

redis:
  addr: ${REDIS_ADDR}
  db: 0
  password: ""

oidc:
  issuer: ${OIDC_ISSUER}
  client_id: ${OIDC_CLIENT_ID}
  client_secret: ${OIDC_CLIENT_SECRET}
  scopes: ["openid","profile","email"]

apps:
  - id: "portfolio-web"
    hosts: ["localhost"]     # identify app by Host. for multiple apps add more blocks.
    base_path: "/"
    cookie:
      name: "__Host-sid"
      same_site: "Lax"
      max_age_seconds: 2592000
    csrf:
      enabled: true
      header: "X-CSRF-Token"
    frontend:
      login_redirect: "/"
      logout_redirect: "/"
      allowed_redirects: ["/","/dashboard","/settings"]
      allowed_origins: ["http://localhost:8080"]
    sessions:
      access_skew_seconds: 60
      refresh_ahead_seconds: 300
      ttl_seconds: 2592000
      single_session_per_user: false
    upstreams:
      - name: "portfolio-api"
        match:
          path_prefix: "/api/portfolio"
          methods: ["GET","POST","PUT","DELETE"]
        forward:
          url: "http://portfolio-api:8000"   # replace with your backend
          strip_prefix: "/api/portfolio"
          timeout_ms: 10000
        auth:
          send_bearer: true
          require:
            any_roles: ["portfolio.user"]
        limits:
          per_ip_rps: 10
          per_user_rps: 20
